IPV4_ONLY and IPV6_ONLY environment control added (#235)

diff --git a/apprise_api/supervisord-startup b/apprise_api/supervisord-startup
--- a/apprise_api/supervisord-startup
+++ b/apprise_api/supervisord-startup
@@ -70,6 +70,22 @@ sed -i -e "s/^\(user[ \t]*=[ \t]*\).*$/\1$USER/g" \
 sed -i -e "s/^\(group[ \t]*=[ \t]*\).*$/\1$GROUP/g" \
    /opt/apprise/webapp/etc/supervisord.conf
 
+if [ "${IPV4_ONLY+x}" ] && [ "${IPV6_ONLY+x}" ]; then
+  echo -n "Warning: both IPV4_ONLY and IPV6_ONLY flags set; ambigious; no changes made."
+
+# Handle IPV4_ONLY flag
+elif [ "${IPV4_ONLY+x}" ]; then
+  echo -n "Enforcing Exclusive IPv4 environment... "
+  sed -ibak -e '/IPv6 Support/d' /opt/apprise/webapp/etc/nginx.conf /opt/apprise/webapp/gunicorn.conf.py && \
+     echo "Done." || echo "Failed!"
+
+# Handle IPV6_ONLY flag
+elif [ "${IPV6_ONLY+x}" ]; then
+  echo -n "Enforcing Exclusive IPv6 environment... "
+  sed -ibak -e '/IPv4 Support/d' /opt/apprise/webapp/etc/nginx.conf /opt/apprise/webapp/gunicorn.conf.py && \
+     echo "Done." || echo "Failed!"
+fi
+
 # Working directory
 cd /opt/apprise
 
